package server

import (
	"log/slog"
	"net/http"
	"net/url"
	"path/filepath"
	"strings"

	"github.com/AliJabbar034/vrok/internal/security"
	"github.com/AliJabbar034/vrok/internal/sharing"
	"github.com/AliJabbar034/vrok/web/viewer"
)

// dispatcher turns a URL into a share request and hands it to the handler for
// that share's kind.
//
// This is the only place that converts a visitor-supplied token into a share,
// and the only place that decides a request is allowed to proceed. Handlers
// downstream can assume the share exists, is available, and is unlocked.
type dispatcher struct {
	resolver sharing.Resolver
	guards   sharing.Guard
	clock    sharing.Clock
	gate     *Gate
	pages    *pages
	logger   *slog.Logger
	handlers map[sharing.Kind]ShareHandler
}

// ServeHTTP handles every /s/{token} request.
func (d *dispatcher) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	sr, ok := d.resolve(w, r, r.PathValue("token"), r.PathValue("rest"))
	if !ok {
		return
	}

	handler, ok := d.handlers[sr.Spec.Kind]
	if !ok {
		d.pages.gone(w, r, nil)
		return
	}
	if !methodAllowed(r, sr) {
		w.Header().Set("Allow", "GET, HEAD")
		http.Error(w, "Method not allowed.", http.StatusMethodNotAllowed)
		return
	}

	// Password check happens after availability and before any content: an
	// expired share must not even show its unlock form.
	if !d.gate.Allow(w, r, sr) {
		return
	}

	sr.Share.Touch(sr.Now)
	handler.ServeShare(w, r, sr)
}

// resolve validates the token, the share's availability and the request path.
// It writes the response itself when the request cannot proceed.
func (d *dispatcher) resolve(w http.ResponseWriter, r *http.Request, token, rest string) (*shareRequest, bool) {
	share, err := d.resolver.ByToken(token)
	if err != nil {
		d.pages.gone(w, r, nil)
		return nil, false
	}

	now := d.clock.Now()
	snap := share.Snapshot()
	if err := d.guards.Check(snap, now); err != nil {
		d.pages.gone(w, r, err)
		return nil, false
	}

	rel, err := relativePath(rest)
	if err != nil {
		d.pages.gone(w, r, nil)
		return nil, false
	}

	return &shareRequest{
		Share:    share,
		Spec:     snap.Spec,
		Snap:     snap,
		Rel:      rel,
		Delivery: parseDelivery(r),
		Links:    NewLinks(snap.Token),
		Now:      now,
	}, true
}

// strays proxies requests that arrive outside any share prefix but were
// triggered from inside an HTTP share.
//
// A dev server that emits absolute asset paths ("/assets/app.js") would
// otherwise 404 the moment it is served under /s/<token>/. The Referer tells
// us which share the browser was looking at, which is enough to route the
// request without asking the user to configure a base path.
func (d *dispatcher) strays(w http.ResponseWriter, r *http.Request) {
	token, ok := tokenFromReferer(r)
	if !ok {
		d.pages.gone(w, r, nil)
		return
	}

	sr, ok := d.resolve(w, r, token, strings.TrimPrefix(r.URL.Path, "/"))
	if !ok {
		return
	}
	// Only HTTP shares have this problem; a file share's paths are all
	// generated by vrok and already carry the prefix.
	if sr.Spec.Kind != sharing.KindHTTP {
		d.pages.gone(w, r, nil)
		return
	}
	if !d.gate.Allow(w, r, sr) {
		return
	}

	d.handlers[sharing.KindHTTP].ServeShare(w, r, sr)
}

// methodAllowed restricts file shares to reads. HTTP shares pass everything
// through, because the application behind them decides what it accepts.
func methodAllowed(r *http.Request, sr *shareRequest) bool {
	if sr.Spec.Kind == sharing.KindHTTP {
		return true
	}
	switch r.Method {
	case http.MethodGet, http.MethodHead:
		return true
	case http.MethodPost:
		// The only POST a file share understands is an unlock submission.
		return sr.Spec.Protected()
	default:
		return false
	}
}

// relativePath normalises the visitor-supplied remainder of a share URL into a
// slash-separated path that cannot escape the share root.
func relativePath(rest string) (string, error) {
	cleaned, err := security.CleanRelative(rest)
	if err != nil {
		return "", err
	}
	if cleaned == "." {
		return "", nil
	}
	return filepath.ToSlash(cleaned), nil
}

// tokenFromReferer extracts a share token from the Referer header.
func tokenFromReferer(r *http.Request) (string, bool) {
	referer := r.Header.Get("Referer")
	if referer == "" {
		return "", false
	}
	u, err := url.Parse(referer)
	if err != nil || !strings.HasPrefix(u.Path, sharePrefix) {
		return "", false
	}
	token, _, _ := strings.Cut(strings.TrimPrefix(u.Path, sharePrefix), "/")
	if token == "" {
		return "", false
	}
	return token, true
}

// newRouter wires the URL space.
//
// Everything vrok owns lives under /s/ or /_vrok/, so no share path can ever
// shadow a vrok route.
func newRouter(d *dispatcher) http.Handler {
	mux := http.NewServeMux()

	mux.Handle(sharePrefix+"{token}", d)
	mux.Handle(sharePrefix+"{token}/{rest...}", d)
	mux.Handle(staticPrefix+"/", staticHandler())

	// Liveness for tunnels and relays, which need a cheap endpoint that is
	// not tied to any share.
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Write([]byte("ok\n"))
	})

	mux.HandleFunc("/", d.strays)
	return mux
}

// staticHandler serves the viewer's embedded CSS and icon.
func staticHandler() http.Handler {
	files := http.FileServerFS(viewer.StaticFS())
	return http.StripPrefix(staticPrefix, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Assets are embedded in the binary, so they only change when vrok
		// does; an hour of caching saves a round trip per page view.
		w.Header().Set("Cache-Control", "public, max-age=3600")
		files.ServeHTTP(w, r)
	}))
}
