#!/usr/bin/env bash
# Share a file behind a password, and watch the unlock exchange.
#
# --password normally prompts. VROK_PASSWORD is how you supply one in a
# script; the plaintext is hashed with Argon2id and discarded.
#
# Run: ./examples/share-protected.sh
set -euo pipefail

VROK="$(dirname "$0")/../bin/vrok"
[ -x "$VROK" ] || { echo "run 'make build' first"; exit 1; }

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"; kill ${share_pid:-0} 2>/dev/null || true' EXIT

echo 'the quarterly numbers' > "$workdir/report.txt"

echo "== sharing with a password =="
VROK_PASSWORD='correct horse battery staple' \
  "$VROK" "$workdir/report.txt" --password --ttl 5m > "$workdir/out.txt" 2>&1 &
share_pid=$!
sleep 1.5

url=$(grep 'URL:' "$workdir/out.txt" | grep -oE 'http://[^ ]+')
cat "$workdir/out.txt"

echo
echo "== without a password: 401, and no hint about what is inside =="
curl -s -o "$workdir/locked.html" -w '  status: %{http_code}\n' "$url"
if grep -q 'report.txt' "$workdir/locked.html"; then
  echo "  LEAK: the filename appeared on the locked page"
else
  echo "  the filename does not appear on the locked page"
fi

echo
echo "== the wrong password: 401 again, after a deliberate delay =="
curl -s -o /dev/null -w '  status: %{http_code}, took %{time_total}s\n' \
  -X POST --data-urlencode 'password=hunter2' "$url"

echo
echo "== the right password: 303 to the file, plus a cookie =="
curl -s -o /dev/null -D "$workdir/headers.txt" \
  -X POST --data-urlencode 'password=correct horse battery staple' "$url"
grep -iE '^HTTP|^location|^set-cookie' "$workdir/headers.txt" | sed 's/^/  /'

echo
echo "== the cookie is a signature, not the password =="
if grep -qi 'horse' "$workdir/headers.txt"; then
  echo "  LEAK: the password is in the cookie"
else
  echo "  no part of the password appears in the cookie"
fi

echo
echo "== with the cookie, the content is served =="
curl -s -c "$workdir/jar" -b "$workdir/jar" \
  -X POST --data-urlencode 'password=correct horse battery staple' -L "$url" \
  | grep -o 'quarterly numbers' | sed 's/^/  found: /'

echo
echo "The cookie is signed with a key generated by this process, so every"
echo "cookie vrok issued stops working the moment it exits."
